version: "3.9"

services:
  ecommerce:
    build: .
    container_name: ecommerce-app
    ports:
     "8090:3000"
    volumes:
      - ./database:/app/database
      - ./vite.config.ts:/app/vite.config.ts
    restart: always